services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: rag
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "${USER_ID:-1000}"
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/dashboard-providers:/etc/grafana/provisioning/dashboards
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
    depends_on:
      - postgres

  frontend:
    image: frontend:latest
    container_name: frontend
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=rag
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - LANCEDB_URI=/app/lancedb
      - BEDROCK_ACCESS_KEY=${BEDROCK_ACCESS_KEY}
      - BEDROCK_SECRET_KEY=${BEDROCK_SECRET_KEY}
    volumes:
      - ./volumes/lancedb:/app/lancedb
    ports:
      - "8501:8501"
    depends_on:
      - postgres
